### PR TITLE
Fix Rspecs

### PR DESCRIPTION
**Pull request by llivne**
Renaming FlashSystems/SVC with IBM_FlashSystems following autosde_client Gem update

### CODE REVIEW

**Comment by llivne** [comment]
@miq-bot add_label morphy/yes?

**Comment by agrare** [comment]
Hey @llivne what version of the gem introduced this?  We should bump the required version in our gemspec to that so that it is obvious what changed here

**Comment by llivne** [comment]
> Hey @llivne what version of the gem introduced this? We should bump the required version in our gemspec to that so that it is obvious what changed here

@agrare it was a minor change, that didnt required changes in miq (I also tested it in morphy) except in the RSPECS, I dont think we should change the gem version to 1.2 (we are currently on 1.1.x)

we changed the storage system type from flashsystem/svc to IBM_flashsystems. the brand name svc is outdated and not used anymore.

**Review by agrare — APPROVED** [review]

**Comment by Fryguy** [comment]
Backported to `najdorf` in commit df0182b61fd1d3985cac90f3023d000ec05ddf65.

```text
commit df0182b61fd1d3985cac90f3023d000ec05ddf65
Author: Adam Grare <adam@grare.com>
Date:   Tue Mar 29 12:34:21 2022 -0400

    Merge pull request #144 from Autosde/fix_rspecs
    
    Fix Rspecs
    
    (cherry picked from commit 4708714d126411bd14646d714b26a68fc0567ef4)
```

**Pull request merged**
