### PR TITLE
storage service resource attachment collection

### PR DESCRIPTION
**Pull request by OrGur1987**
see issue: https://github.com/ManageIQ/manageiq-providers-autosde/issues/202

### CODE REVIEW

**Comment by OrGur1987** [comment]
> 

@agrare any idea regarding the cassette problem?

**Comment by OrGur1987** [comment]
> failure in specs doesn't happen when I run them locally. The updated cassette has 9 attachments, not sure why this fails
> 
> ```
> 1) ManageIQ::Providers::Autosde::StorageManager::Refresher#refresh full refresh Performs a full refresh
>      Failure/Error: expect(ems.storage_service_resource_attachments.count).to(eq(9))
> 
>        expected: 9
>             got: 0
> 
>        (compared using ==)
>      # ./spec/models/manageiq/providers/autosde/storage_manager/refresher_spec.rb:225:in `assert_ems'
>      # ./spec/models/manageiq/providers/autosde/storage_manager/refresher_spec.rb:17:in `block (5 levels) in <top (required)>'
>      # ./spec/models/manageiq/providers/autosde/storage_manager/refresher_spec.rb:13:in `times'
>      # ./spec/models/manageiq/providers/autosde/storage_manager/refresher_spec.rb:13:in `block (4 levels) in <top (required)>'
> ```

@agrare any idea regarding this problem?

**Comment by agrare** [comment]
@OrGur1987 fails locally for me also.  My :dollar: is on it passing locally for you because you have https://github.com/ManageIQ/manageiq/pull/22332 applied locally.  You can run a cross-repo test including that PR to show that the combination works.

**Comment by OrGur1987** [comment]
@miq-bot cross-repo-tests ManageIQ/manageiq#22332

**Comment by OrGur1987** [comment]
> @miq-bot cross-repo-tests [ManageIQ/manageiq#22332](https://github.com/ManageIQ/manageiq/pull/22332)

Passed

**Review by agrare — APPROVED** [review]

**Pull request merged**
