### PR TITLE
[MORPHY] [LASKER] fix broken rspecs

### PR DESCRIPTION
**Pull request by llivne**
remove redundent / from urls in rspecs

This PR need to be backport to both morphy and lasker. Note that I used morphy as the base 

the solution was already merged into master under https://github.com/ManageIQ/manageiq-providers-autosde/pull/75 which is a mixed PR of both rspecs bug fixes and enhancement, so I made this specific PR for only the bug fix.

### CODE REVIEW

**Review by agrare — APPROVED** [review]

**Comment by Fryguy** [comment]
@llivne A conflict occurred during the backport of this pull request to `lasker`.

If this pull request is based on another pull request that has not been marked for backport, add the appropriate labels to the other pull request. Otherwise, please create a new pull request direct to the `lasker` branch in order to resolve this.

Conflict details:

```diff
diff --cc spec/vcr_cassettes/bad_token_get_storage_systems_with_relogin_not_fails.yml
index 384bde5,4749a87..0000000
--- a/spec/vcr_cassettes/bad_token_get_storage_systems_with_relogin_not_fails.yml
+++ b/spec/vcr_cassettes/bad_token_get_storage_systems_with_relogin_not_fails.yml
@@@ -119,7 -119,7 +119,11 @@@ http_interactions
    recorded_at: Sat, 18 Jul 2020 14:45:18 GMT
  - request:
      method: get
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/storage-systems/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/storage-systems
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: US-ASCII
        string: ''
@@@ -201,7 -201,7 +205,11 @@@
    recorded_at: Sun, 19 Jul 2020 10:50:22 GMT
  - request:
      method: get
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/storage-systems/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/storage-systems
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: US-ASCII
        string: ''
diff --cc spec/vcr_cassettes/check_state_exists.yml
index a2d6184,9c62da6..0000000
--- a/spec/vcr_cassettes/check_state_exists.yml
+++ b/spec/vcr_cassettes/check_state_exists.yml
@@@ -2,7 -2,7 +2,11 @@@
  http_interactions:
  - request:
      method: post
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/token-auth/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/token-auth
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: UTF-8
        string: '{"username":"<username>","password":"<password>"}'
@@@ -41,7 -41,7 +45,11 @@@
    recorded_at: Sun, 28 Jun 2020 11:20:35 GMT
  - request:
      method: get
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/volumes/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/volumes
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: US-ASCII
        string: ''
diff --cc spec/vcr_cassettes/create_new_volume.yml
index 34a40cb,18e821b..0000000
--- a/spec/vcr_cassettes/create_new_volume.yml
+++ b/spec/vcr_cassettes/create_new_volume.yml
@@@ -2,7 -2,7 +2,11 @@@
  http_interactions:
  - request:
      method: post
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/volumes/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/volumes
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: UTF-8
        string: '{"compliant":false,"name":"vol_test_bk_2020-06-28 14_20_35","service":"6ac78be9-d6cc-4c3f-8882-bec5e6be1dc3","size":10}'
diff --cc spec/vcr_cassettes/ems_refresh.yml
index ad4f790,0d10beb..0000000
--- a/spec/vcr_cassettes/ems_refresh.yml
+++ b/spec/vcr_cassettes/ems_refresh.yml
@@@ -41,7 -41,7 +41,11 @@@ http_interactions
    recorded_at: Thu, 07 Jan 2021 09:35:16 GMT
  - request:
      method: get
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/system-types/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/system-types
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: US-ASCII
        string: ''
@@@ -125,7 -125,7 +129,11 @@@
  
  - request:
      method: get
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/storage-systems/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/storage-systems
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: US-ASCII
        string: ''
@@@ -166,7 -166,7 +174,11 @@@
    recorded_at: Thu, 07 Jan 2021 09:35:16 GMT
  - request:
      method: get
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/storage-resources/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/storage-resources
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: US-ASCII
        string: ''
@@@ -248,7 -248,7 +260,11 @@@
    recorded_at: Thu, 07 Jan 2021 09:35:16 GMT
  - request:
      method: get
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/services/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/services
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: US-ASCII
        string: ''
@@@ -289,7 -289,7 +305,11 @@@
    recorded_at: Thu, 07 Jan 2021 09:35:16 GMT
  - request:
      method: get
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/volumes/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/volumes
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: US-ASCII
        string: ''
diff --cc spec/vcr_cassettes/get_service_resource_attachment.yml
index 2ec3652,e8a91be..0000000
--- a/spec/vcr_cassettes/get_service_resource_attachment.yml
+++ b/spec/vcr_cassettes/get_service_resource_attachment.yml
@@@ -2,7 -2,7 +2,11 @@@
  http_interactions:
  - request:
      method: get
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/service-resource-attchment/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/service-resource-attchment
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: US-ASCII
        string: ''
diff --cc spec/vcr_cassettes/get_services.yml
index d2c792e,70f4a48..0000000
--- a/spec/vcr_cassettes/get_services.yml
+++ b/spec/vcr_cassettes/get_services.yml
@@@ -2,7 -2,7 +2,11 @@@
  http_interactions:
  - request:
      method: get
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/services/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/services
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: US-ASCII
        string: ''
diff --cc spec/vcr_cassettes/get_storage_resources.yml
index f6827aa,c2c5404..0000000
--- a/spec/vcr_cassettes/get_storage_resources.yml
+++ b/spec/vcr_cassettes/get_storage_resources.yml
@@@ -2,7 -2,7 +2,11 @@@
  http_interactions:
  - request:
      method: get
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/storage-resources/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/storage-resources
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: US-ASCII
        string: ''
diff --cc spec/vcr_cassettes/get_storage_system.yml
index 19f9d62,91415d2..0000000
--- a/spec/vcr_cassettes/get_storage_system.yml
+++ b/spec/vcr_cassettes/get_storage_system.yml
@@@ -2,7 -2,7 +2,11 @@@
  http_interactions:
  - request:
      method: post
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/token-auth/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/token-auth
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: UTF-8
        string: '{"username":"<username>","password":"<password>"}'
@@@ -41,7 -41,7 +45,11 @@@
    recorded_at: Sun, 28 Jun 2020 11:20:35 GMT
  - request:
      method: get
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/storage-systems/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/storage-systems
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: US-ASCII
        string: ''
diff --cc spec/vcr_cassettes/get_storage_systems_autosde_client.yml
index 6133235,044c773..0000000
--- a/spec/vcr_cassettes/get_storage_systems_autosde_client.yml
+++ b/spec/vcr_cassettes/get_storage_systems_autosde_client.yml
@@@ -2,7 -2,7 +2,11 @@@
  http_interactions:
  - request:
      method: post
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/token-auth/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/token-auth
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: UTF-8
        string: '{"username":"<username>","password":"<password>"}'
@@@ -41,7 -41,7 +45,11 @@@
    recorded_at: Thu, 02 Jul 2020 09:49:02 GMT
  - request:
      method: get
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/storage-systems/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/storage-systems
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: US-ASCII
        string: ''
diff --cc spec/vcr_cassettes/get_storage_systems_from_storage_manager.yml
index 3a1772d,996ef9d..0000000
--- a/spec/vcr_cassettes/get_storage_systems_from_storage_manager.yml
+++ b/spec/vcr_cassettes/get_storage_systems_from_storage_manager.yml
@@@ -2,7 -2,7 +2,11 @@@
  http_interactions:
  - request:
      method: post
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/token-auth/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/token-auth
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: UTF-8
        string: '{"username":"<username>","password":"<password>"}'
@@@ -41,7 -41,7 +45,11 @@@
    recorded_at: Mon, 13 Jul 2020 12:50:15 GMT
  - request:
      method: get
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/storage-systems/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/storage-systems
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: US-ASCII
        string: ''
diff --cc spec/vcr_cassettes/get_volumes.yml
index 9faf7c1,7ad54b8..0000000
--- a/spec/vcr_cassettes/get_volumes.yml
+++ b/spec/vcr_cassettes/get_volumes.yml
@@@ -2,7 -2,7 +2,11 @@@
  http_interactions:
  - request:
      method: get
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/volumes/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/volumes
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: US-ASCII
        string: ''
diff --cc spec/vcr_cassettes/get_volumes_after_creation.yml
index 91eb456,dceb607..0000000
--- a/spec/vcr_cassettes/get_volumes_after_creation.yml
+++ b/spec/vcr_cassettes/get_volumes_after_creation.yml
@@@ -2,7 -2,7 +2,11 @@@
  http_interactions:
  - request:
      method: get
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/volumes/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/volumes
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: US-ASCII
        string: ''
diff --cc spec/vcr_cassettes/incorrect_login_spec.yml
index ed2d11a,df87635..0000000
--- a/spec/vcr_cassettes/incorrect_login_spec.yml
+++ b/spec/vcr_cassettes/incorrect_login_spec.yml
@@@ -2,7 -2,7 +2,11 @@@
  http_interactions:
  - request:
      method: post
++<<<<<<< HEAD
 +    uri: https://9.151.190.206/site-manager/api/v1/engine/token-auth/
++=======
+     uri: https://autosde-appliance-host/site-manager/api/v1/engine/token-auth
++>>>>>>> 6cf15cb... Merge pull request #84 from llivne/fix_broken_rspecs
      body:
        encoding: UTF-8
        string: '{"username":"<username>","password":"<password>"}'
```

**Comment by agrare** [comment]
@llivne when there is a conflict on backport you have to resolve it in a timely manner as this blocks backporting other PRs

**Comment by llivne** [comment]
> @llivne when there is a conflict on backport you have to resolve it in a timely manner as this blocks backporting other PRs

@agrare I missed the msg @Fryguy wrote a few days ago. I will work on it tommorow

**Comment by agrare** [comment]
Backporting via https://github.com/ManageIQ/manageiq-providers-autosde/pull/106

**Comment by Fryguy** [comment]
Backported via #106

**Comment by llivne** [comment]
> > @llivne when there is a conflict on backport you have to resolve it in a timely manner as this blocks backporting other PRs
> 
> @agrare I missed the msg @Fryguy wrote a few days ago. I will work on it tommorow

@agrare @Fryguy I see that the issue was resolved by you. if you need anything else from me please let me know.

**Pull request merged**
