### PR TITLE
[WIP]changed sizes to gb

### PR DESCRIPTION
**Pull request by IlyaKessel**
Added size conversion to GB

### CODE REVIEW

**Comment by chessbyte** [comment]
@agrare does this align with the other providers?

**Comment by agrare** [comment]
Unless otherwise noted all storage sizes in the db should be in bytes

**Comment by Fryguy** [comment]
Also the rubocops should be addressed.

**Comment by gregoryb-at-ibm** [comment]
So we need to redo this and normalize everything to bytes.

**Comment by erantzabari** [comment]
We agree that it should all be presented in Bytes.

**Pull request closed without merging**
