### PR TITLE
Update storage system args

### PR DESCRIPTION
**Pull request by tzurvaza**
Remove deprecated args (auto_add_pools, auto_setup)

### CODE REVIEW

**Review by agrare — APPROVED** [review]

**Comment by agrare** [comment]
@tzurvaza @eilam20 what version of the gem were these removed in?  This was a breaking change in the `v1.1.0` branch and is causing failures on the najdorf release branch.

**Comment by agrare** [comment]
It looks like these were removed in `v1.1.33`

**Comment by agrare** [comment]
@tzurvaza what was added in .33 and .34?  Is it anything we need for oparin? (NOTE we already locked oparin to 1.1.34)

**Comment by tzurvaza** [comment]
@agrare nothing from .33-.34 used by the oparin branch

**Pull request merged**
