### PR TITLE
change version to 2.0.0 after changes in the autosde api

### PR DESCRIPTION
**Pull request by eilam20**
We made changes in the autosde api.
Now we return a response with pagination, so we need to upgrade the gem version to 2.0.0

### CODE REVIEW

**Comment by agrare** [comment]
@eilam20 curious how this passes with the new gem but without re-recording the VCRs if the API response is different?

**Comment by eilam20** [comment]
This gem version will accept response from old autosde versions but we need to adjust it to the new paginated response that the new version of autosde will return.

**Comment by agrare** [comment]
@eilam20 sounds good, do you want to split your VCRs into v1 and v2 to ensure both paths work?

**Comment by eilam20** [comment]
@agrare hi I split the specs into two versions, can you check it?

**Review by agrare — APPROVED** [review]
LGTM!

**Pull request merged**
