### PR TITLE
326047 Add capabilities schema and relations

### PR DESCRIPTION
**Pull request by galoiring**
We added capability and capability values schema. 
W/ @OrGur1987 

main repo PR: https://github.com/ManageIQ/manageiq/pull/22137
schema PR: https://github.com/ManageIQ/manageiq-schema/pull/667

Screen Shot 2022-10-02 at 18 13 04

### CODE REVIEW

**Comment by OrGur1987** [comment]
this can be closed, sorry

**Comment by kbrock** [comment]
@OrGur1987 Do you still want https://github.com/ManageIQ/manageiq/pull/22137 to be open?

**Comment by OrGur1987** [comment]
> @OrGur1987 Do you still want [ManageIQ/manageiq#22137](https://github.com/ManageIQ/manageiq/pull/22137) to be open?

no, we took Adam's and Jason's approach to adding capabilities as json fields.
thanks

**Comment by kbrock** [comment]
> this can be closed, sorry

Ok closing.
Thanks again for all the help on the project

**Pull request closed without merging**
