### PR TITLE
Sde 460 volume service catalog

### PR DESCRIPTION
**Pull request by eilam20**
Add support to catalog for autosde

### CODE REVIEW

**Comment by agrare** [comment]
Hey @eilam20 it looks like you have some changes here from master as part of this commit https://github.com/ManageIQ/manageiq-providers-autosde/pull/157/commits/b062e17cef0f3cff2f3941d40a8b18ef4a190478

Please rebase your branch rather than merging, this helps us cut down on extra merge commits and keeps the PRs clean.

Personally I use `git config --global pull.rebase` so that I can simply `git pull upstream master` and it does the right thing.

**Review by llivne — APPROVED** [review]

**Comment by eilam20** [comment]
hi, I did the rebase. can you review it?

**Comment by agrare** [comment]
@eilam20 I still see https://github.com/ManageIQ/manageiq-providers-autosde/pull/157/commits/22073d6926808c15e7ff103ee66a8ef1bf3a4371 it looks like https://github.com/ManageIQ/manageiq-providers-autosde/pull/157/commits/62f027bb7c55c20e4650bb638b84f4bd63ca33d2 added that file then `merge` removed it.  Wonder if it'd be better to rebase these commits into just one since the changeset is pretty simple

**Comment by eilam20** [comment]
@agrare done, can you review it?

**Review by agrare — APPROVED** [review]

**Comment by eilam20** [comment]
> @eilam20 can you confirm this still works? We had to make changes to fix failing tests in core

its still works ok.

**Pull request merged**
